# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20170607_0401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='isemail',
            new_name='issuper',
        ),
        migrations.RemoveField(
            model_name='account',
            name='isphone',
        ),
    ]
