# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_auto_20170611_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='issuper',
            new_name='isadministrator',
        ),
    ]
