# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isemail',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='isphone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
