# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20170607_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='isemail',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='isphone',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
